#!/usr/bin/env python3
"""Regenerate src/ItemData.elm from the WalkScape Tools API.

    python3 scripts/import-items.py

Keeps only items the game marks `canBeTraded`. Ids are the API's own
(snake_case, e.g. "iron_pickaxe"); they appear in URLs and in stored listings,
so renaming one in the game orphans its old listings. Run
scripts/pull-icons.py afterwards to fetch icons for any new items.
"""

import os

from walkscape_api import ROOT, call

# The search endpoint needs at least one filter, so ask for each type in turn.
TYPES = ["loot", "crafted", "material", "consumable", "collectible", "container", "currency", "egg", "lore"]
OUT = os.path.join(ROOT, "src", "ItemData.elm")


def elm_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    items = []
    skipped = 0
    for kind in TYPES:
        for item in call(f"/items/search?type={kind}&detailed=true"):
            if item.get("canBeTraded"):
                items.append((item["id"], item["name"], item["type"], item.get("quality") or "common", bool(item.get("canBeFine"))))
            else:
                skipped += 1
    if len(items) < 100:
        raise SystemExit(f"Only found {len(items)} tradeable items; has the API changed?")
    rows = "\n    , ".join(
        f"( {elm_string(id_)}, {elm_string(name)}, ( {elm_string(kind)}, {elm_string(rarity)}, {'True' if fine else 'False'} ) )"
        for id_, name, kind, rarity, fine in sorted(items, key=lambda i: i[1].lower())
    )
    open(OUT, "w").write(f'''module ItemData exposing (raw)

{{-| GENERATED by scripts/import-items.py from the WalkScape Tools API. Don't
edit by hand.

Each entry is (id, name, (type, rarity, canBeFine)), for every item the game
allows to be traded. Type is the game's: loot, crafted, material, consumable,
collectible, container, currency or egg.

-}}


raw : List ( String, String, ( String, String, Bool ) )
raw =
    [ {rows}
    ]
''')
    print(f"Wrote {len(items)} tradeable items to src/ItemData.elm ({skipped} untradeable skipped).")


main()
