#!/usr/bin/env python3
"""Regenerate src/ItemData.elm from walkscapedb.com/items.

    python3 scripts/import-items.py            # fetch and write
    python3 scripts/import-items.py page.html  # parse a saved copy instead

walkscapedb.com is a fan site, so this is a stopgap until there's an official
WalkScape API. Currency and lore items are skipped since they can't be traded.
"""
import html
import re
import sys
import urllib.request

URL = "https://walkscapedb.com/items"
SKIP_TYPES = {"currency", "lore"}
OUT = "src/ItemData.elm"


def fetch():
    req = urllib.request.Request(URL, headers={"User-Agent": "Trailpost item import (fan project)"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read().decode("utf-8")


def parse(page):
    items = []
    for tag, body in re.findall(r'(<tr data-name="[^"]*"[^>]*class="item-row[^>]*>)(.*?)</tr>', page, re.S):
        attrs = dict(re.findall(r'(data-[a-z-]+)="([^"]*)"', tag))
        link = re.search(r'<a href="/items/[^"]+"[^>]*>([^<]+)</a>', body)
        if not link or not attrs.get("data-item-slug"):
            continue
        kind = attrs.get("data-filter-type", "")
        if kind in SKIP_TYPES:
            continue
        items.append((attrs["data-item-slug"], html.unescape(link.group(1)).strip(), kind, attrs.get("data-quality", "common")))
    return items


def elm_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    page = open(sys.argv[1]).read() if len(sys.argv) > 1 else fetch()
    items = parse(page)
    if len(items) < 100:
        sys.exit(f"Only found {len(items)} items; the page layout probably changed.")
    rows = "\n    , ".join(
        f"( {elm_string(slug)}, {elm_string(name)}, ( {elm_string(kind)}, {elm_string(rarity)} ) )"
        for slug, name, kind, rarity in sorted(items, key=lambda i: i[1].lower())
    )
    open(OUT, "w").write(f'''module ItemData exposing (raw)

{{-| GENERATED by scripts/import-items.py from {URL}. Don't edit by hand.

Each entry is (slug, name, (type, rarity)). Type is walkscapedb's category:
loot, crafted, material, consumable, collectible, container or egg.

-}}


raw : List ( String, String, ( String, String ) )
raw =
    [ {rows}
    ]
''')
    print(f"Wrote {len(items)} items to {OUT}")


main()
