module Evergreen.Migrate.V17 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V15.Auth.Common
import Evergreen.V15.Item
import Evergreen.V15.OAuth
import Evergreen.V15.OAuth.AuthorizationCode
import Evergreen.V15.Route
import Evergreen.V15.Types
import Evergreen.V17.Auth.Common
import Evergreen.V17.Item
import Evergreen.V17.OAuth
import Evergreen.V17.OAuth.AuthorizationCode
import Evergreen.V17.Route
import Evergreen.V17.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V15.Types.FrontendModel -> ModelMigration Evergreen.V17.Types.FrontendModel Evergreen.V17.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V15.Types.BackendModel -> ModelMigration Evergreen.V17.Types.BackendModel Evergreen.V17.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V15.Types.FrontendMsg -> MsgMigration Evergreen.V17.Types.FrontendMsg Evergreen.V17.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V15.Types.ToBackend -> MsgMigration Evergreen.V17.Types.ToBackend Evergreen.V17.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V15.Types.BackendMsg -> MsgMigration Evergreen.V17.Types.BackendMsg Evergreen.V17.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V15.Types.ToFrontend -> MsgMigration Evergreen.V17.Types.ToFrontend Evergreen.V17.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V15.Types.FrontendModel -> Evergreen.V17.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , now = old.now
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    , me = old.me |> Maybe.map migrate_Types_Me
    , loaded = old.loaded
    , listings = old.listings |> Dict.map (\k -> migrate_Types_Listing)
    , offers = old.offers |> Dict.map (\k -> migrate_Types_Offer)
    , traders = old.traders
    , filters = old.filters |> migrate_Types_MarketFilters
    , noticeDismissed = old.noticeDismissed
    , filtersOpen = old.filtersOpen
    , claimName = old.claimName
    , claimError = old.claimError
    , listingForm = old.listingForm |> migrate_Types_ListingForm
    , offerForm = old.offerForm |> migrate_Types_OfferForm
    , reportForm = old.reportForm |> migrate_Types_ReportForm
    , previewSignInFor = old.previewSignInFor |> Maybe.map migrate_Types_Provider
    , toast = old.toast
    , tradesTab = old.tradesTab |> migrate_Types_TradesTab
    , admin = old.admin |> Maybe.map migrate_Types_AdminData
    , adminPage = old.adminPage |> migrate_Types_AdminPage
    }


migrate_Auth_Common_Error : Evergreen.V15.Auth.Common.Error -> Evergreen.V17.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V15.Auth.Common.ErrStateMismatch ->
            Evergreen.V17.Auth.Common.ErrStateMismatch

        Evergreen.V15.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V17.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V15.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V17.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V15.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V17.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V15.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V17.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V15.Auth.Common.ErrAuthString p0 ->
            Evergreen.V17.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V15.Auth.Common.Flow -> Evergreen.V17.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V15.Auth.Common.Idle ->
            Evergreen.V17.Auth.Common.Idle

        Evergreen.V15.Auth.Common.Requested p0 ->
            Evergreen.V17.Auth.Common.Requested p0

        Evergreen.V15.Auth.Common.Pending ->
            Evergreen.V17.Auth.Common.Pending

        Evergreen.V15.Auth.Common.Authorized p0 p1 ->
            Evergreen.V17.Auth.Common.Authorized p0 p1

        Evergreen.V15.Auth.Common.Authenticated p0 ->
            Evergreen.V17.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V15.Auth.Common.Done p0 ->
            Evergreen.V17.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V15.Auth.Common.Errored p0 ->
            Evergreen.V17.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_UserInfo : Evergreen.V15.Auth.Common.UserInfo -> Evergreen.V17.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Item_Quality : Evergreen.V15.Item.Quality -> Evergreen.V17.Item.Quality
migrate_Item_Quality old =
    case old of
        Evergreen.V15.Item.Normal ->
            Evergreen.V17.Item.Normal

        Evergreen.V15.Item.Good ->
            Evergreen.V17.Item.Good

        Evergreen.V15.Item.Great ->
            Evergreen.V17.Item.Great

        Evergreen.V15.Item.Excellent ->
            Evergreen.V17.Item.Excellent

        Evergreen.V15.Item.Perfect ->
            Evergreen.V17.Item.Perfect

        Evergreen.V15.Item.Eternal ->
            Evergreen.V17.Item.Eternal


migrate_Item_Rarity : Evergreen.V15.Item.Rarity -> Evergreen.V17.Item.Rarity
migrate_Item_Rarity old =
    case old of
        Evergreen.V15.Item.Common ->
            Evergreen.V17.Item.Common

        Evergreen.V15.Item.Uncommon ->
            Evergreen.V17.Item.Uncommon

        Evergreen.V15.Item.Rare ->
            Evergreen.V17.Item.Rare

        Evergreen.V15.Item.Epic ->
            Evergreen.V17.Item.Epic

        Evergreen.V15.Item.Legendary ->
            Evergreen.V17.Item.Legendary

        Evergreen.V15.Item.Ethereal ->
            Evergreen.V17.Item.Ethereal


migrate_Item_Variant : Evergreen.V15.Item.Variant -> Evergreen.V17.Item.Variant
migrate_Item_Variant old =
    { fine = old.fine
    , rare = old.rare
    , quality = old.quality |> Maybe.map migrate_Item_Quality
    }


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V15.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V17.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V15.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V17.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V15.OAuth.ErrorCode -> Evergreen.V17.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V15.OAuth.InvalidRequest ->
            Evergreen.V17.OAuth.InvalidRequest

        Evergreen.V15.OAuth.UnauthorizedClient ->
            Evergreen.V17.OAuth.UnauthorizedClient

        Evergreen.V15.OAuth.AccessDenied ->
            Evergreen.V17.OAuth.AccessDenied

        Evergreen.V15.OAuth.UnsupportedResponseType ->
            Evergreen.V17.OAuth.UnsupportedResponseType

        Evergreen.V15.OAuth.InvalidScope ->
            Evergreen.V17.OAuth.InvalidScope

        Evergreen.V15.OAuth.ServerError ->
            Evergreen.V17.OAuth.ServerError

        Evergreen.V15.OAuth.TemporarilyUnavailable ->
            Evergreen.V17.OAuth.TemporarilyUnavailable

        Evergreen.V15.OAuth.Custom p0 ->
            Evergreen.V17.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V15.OAuth.Token -> Evergreen.V17.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V15.OAuth.Bearer p0 ->
            Evergreen.V17.OAuth.Bearer p0


migrate_Route_Route : Evergreen.V15.Route.Route -> Evergreen.V17.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V15.Route.Home ->
            Evergreen.V17.Route.Home

        Evergreen.V15.Route.Market ->
            Evergreen.V17.Route.Market

        Evergreen.V15.Route.Prices ->
            Evergreen.V17.Route.Prices

        Evergreen.V15.Route.ItemPrice p0 p1 ->
            Evergreen.V17.Route.ItemPrice p0 (p1 |> migrate_Item_Variant)

        Evergreen.V15.Route.ListingPage p0 ->
            Evergreen.V17.Route.ListingPage p0

        Evergreen.V15.Route.NewListing ->
            Evergreen.V17.Route.NewListing Nothing

        Evergreen.V15.Route.MyTrades ->
            Evergreen.V17.Route.MyTrades

        Evergreen.V15.Route.Profile p0 ->
            Evergreen.V17.Route.Profile p0

        Evergreen.V15.Route.Report p0 ->
            Evergreen.V17.Route.Report p0

        Evergreen.V15.Route.SignIn ->
            Evergreen.V17.Route.SignIn

        Evergreen.V15.Route.Onboarding ->
            Evergreen.V17.Route.Onboarding

        Evergreen.V15.Route.Admin ->
            Evergreen.V17.Route.Admin

        Evergreen.V15.Route.NotFound ->
            Evergreen.V17.Route.NotFound


migrate_Types_AdminAction : Evergreen.V15.Types.AdminAction -> Evergreen.V17.Types.AdminAction
migrate_Types_AdminAction old =
    case old of
        Evergreen.V15.Types.DeleteListing p0 ->
            Evergreen.V17.Types.DeleteListing p0

        Evergreen.V15.Types.DeleteOffer p0 ->
            Evergreen.V17.Types.DeleteOffer p0

        Evergreen.V15.Types.BanPlayer p0 p1 ->
            Evergreen.V17.Types.BanPlayer p0 p1

        Evergreen.V15.Types.UnbanPlayer p0 ->
            Evergreen.V17.Types.UnbanPlayer p0

        Evergreen.V15.Types.ReleaseName p0 ->
            Evergreen.V17.Types.ReleaseName p0

        Evergreen.V15.Types.SetReportResolved p0 p1 ->
            Evergreen.V17.Types.SetReportResolved p0 p1


migrate_Types_AdminData : Evergreen.V15.Types.AdminData -> Evergreen.V17.Types.AdminData
migrate_Types_AdminData old =
    { accounts = old.accounts
    , users = old.users
    , listings = old.listings |> List.map migrate_Types_Listing
    , offers = old.offers |> List.map migrate_Types_Offer
    , reports = old.reports
    , log = old.log
    }


migrate_Types_AdminPage : Evergreen.V15.Types.AdminPage -> Evergreen.V17.Types.AdminPage
migrate_Types_AdminPage old =
    { tab = old.tab |> migrate_Types_AdminTab
    , search = old.search
    , confirming = old.confirming |> Maybe.map migrate_Types_AdminAction
    , banReason = old.banReason
    }


migrate_Types_AdminTab : Evergreen.V15.Types.AdminTab -> Evergreen.V17.Types.AdminTab
migrate_Types_AdminTab old =
    case old of
        Evergreen.V15.Types.AdminReports ->
            Evergreen.V17.Types.AdminReports

        Evergreen.V15.Types.AdminListings ->
            Evergreen.V17.Types.AdminListings

        Evergreen.V15.Types.AdminPlayers ->
            Evergreen.V17.Types.AdminPlayers

        Evergreen.V15.Types.AdminLog ->
            Evergreen.V17.Types.AdminLog


migrate_Types_Claim : Evergreen.V15.Types.Claim -> Evergreen.V17.Types.Claim
migrate_Types_Claim old =
    { name = old.name
    , status = old.status |> migrate_Types_ClaimStatus
    }


migrate_Types_ClaimStatus : Evergreen.V15.Types.ClaimStatus -> Evergreen.V17.Types.ClaimStatus
migrate_Types_ClaimStatus old =
    case old of
        Evergreen.V15.Types.PreviewUnverified ->
            Evergreen.V17.Types.PreviewUnverified


migrate_Types_Listing : Evergreen.V15.Types.Listing -> Evergreen.V17.Types.Listing
migrate_Types_Listing old =
    { id = old.id
    , trader = old.trader
    , itemId = old.itemId
    , variant = old.variant |> migrate_Item_Variant
    , side = old.side |> migrate_Types_Side
    , payment = old.payment |> migrate_Types_Payment
    , quantity = old.quantity
    , note = old.note
    , createdAt = old.createdAt
    , liveAt = old.liveAt
    , closed = old.closed
    }


migrate_Types_ListingForm : Evergreen.V15.Types.ListingForm -> Evergreen.V17.Types.ListingForm
migrate_Types_ListingForm old =
    { itemQuery = old.itemQuery
    , itemId = old.itemId
    , quality = old.quality |> migrate_Item_Quality
    , fine = old.fine
    , rare = old.rare
    , side = old.side |> migrate_Types_Side
    , quantity = old.quantity
    , price = old.price
    , note = old.note
    , error = old.error
    , submitting = old.submitting
    }


migrate_Types_MarketFilters : Evergreen.V15.Types.MarketFilters -> Evergreen.V17.Types.MarketFilters
migrate_Types_MarketFilters old =
    { tab = old.tab |> migrate_Types_MarketTab
    , rarities = old.rarities |> List.map migrate_Item_Rarity
    , qualities = old.qualities |> List.map migrate_Item_Quality
    , fineOnly = old.fineOnly
    , sort = old.sort |> migrate_Types_MarketSort
    , hideOutliers = old.hideOutliers
    , search = old.search
    }


migrate_Types_MarketSort : Evergreen.V15.Types.MarketSort -> Evergreen.V17.Types.MarketSort
migrate_Types_MarketSort old =
    case old of
        Evergreen.V15.Types.Newest ->
            Evergreen.V17.Types.Newest

        Evergreen.V15.Types.PriceLow ->
            Evergreen.V17.Types.PriceLow

        Evergreen.V15.Types.PriceHigh ->
            Evergreen.V17.Types.PriceHigh


migrate_Types_MarketTab : Evergreen.V15.Types.MarketTab -> Evergreen.V17.Types.MarketTab
migrate_Types_MarketTab old =
    case old of
        Evergreen.V15.Types.AllListings ->
            Evergreen.V17.Types.AllListings

        Evergreen.V15.Types.SellingTab ->
            Evergreen.V17.Types.SellingTab

        Evergreen.V15.Types.BuyingTab ->
            Evergreen.V17.Types.BuyingTab


migrate_Types_Me : Evergreen.V15.Types.Me -> Evergreen.V17.Types.Me
migrate_Types_Me old =
    { provider = old.provider |> migrate_Types_Provider
    , isPreviewLogin = old.isPreviewLogin
    , claim = old.claim |> Maybe.map migrate_Types_Claim
    , isAdmin = old.isAdmin
    , ban = old.ban
    }


migrate_Types_Offer : Evergreen.V15.Types.Offer -> Evergreen.V17.Types.Offer
migrate_Types_Offer old =
    { id = old.id
    , listingId = old.listingId
    , from = old.from
    , price = old.price
    , message = old.message
    , at = old.at
    , status = old.status |> migrate_Types_OfferStatus
    }


migrate_Types_OfferForm : Evergreen.V15.Types.OfferForm -> Evergreen.V17.Types.OfferForm
migrate_Types_OfferForm old =
    old


migrate_Types_OfferStatus : Evergreen.V15.Types.OfferStatus -> Evergreen.V17.Types.OfferStatus
migrate_Types_OfferStatus old =
    case old of
        Evergreen.V15.Types.OfferOpen ->
            Evergreen.V17.Types.OfferOpen

        Evergreen.V15.Types.OfferAccepted ->
            Evergreen.V17.Types.OfferAccepted

        Evergreen.V15.Types.OfferDeclined ->
            Evergreen.V17.Types.OfferDeclined

        Evergreen.V15.Types.OfferWithdrawn ->
            Evergreen.V17.Types.OfferWithdrawn


migrate_Types_Payment : Evergreen.V15.Types.Payment -> Evergreen.V17.Types.Payment
migrate_Types_Payment old =
    case old of
        Evergreen.V15.Types.Coins p0 ->
            Evergreen.V17.Types.Coins p0


migrate_Types_Provider : Evergreen.V15.Types.Provider -> Evergreen.V17.Types.Provider
migrate_Types_Provider old =
    case old of
        Evergreen.V15.Types.Discord ->
            Evergreen.V17.Types.Discord


migrate_Types_ReportForm : Evergreen.V15.Types.ReportForm -> Evergreen.V17.Types.ReportForm
migrate_Types_ReportForm old =
    old


migrate_Types_Side : Evergreen.V15.Types.Side -> Evergreen.V17.Types.Side
migrate_Types_Side old =
    case old of
        Evergreen.V15.Types.Selling ->
            Evergreen.V17.Types.Selling

        Evergreen.V15.Types.Buying ->
            Evergreen.V17.Types.Buying


migrate_Types_TradesTab : Evergreen.V15.Types.TradesTab -> Evergreen.V17.Types.TradesTab
migrate_Types_TradesTab old =
    case old of
        Evergreen.V15.Types.ReceivedTab ->
            Evergreen.V17.Types.ReceivedTab

        Evergreen.V15.Types.SentTab ->
            Evergreen.V17.Types.SentTab

        Evergreen.V15.Types.MyListingsTab ->
            Evergreen.V17.Types.MyListingsTab
