module Evergreen.Migrate.V18 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V17.Auth.Common
import Evergreen.V17.Item
import Evergreen.V17.OAuth
import Evergreen.V17.OAuth.AuthorizationCode
import Evergreen.V17.Route
import Evergreen.V17.Types
import Evergreen.V18.Auth.Common
import Evergreen.V18.Item
import Evergreen.V18.OAuth
import Evergreen.V18.OAuth.AuthorizationCode
import Evergreen.V18.Route
import Evergreen.V18.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V17.Types.FrontendModel -> ModelMigration Evergreen.V18.Types.FrontendModel Evergreen.V18.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V17.Types.BackendModel -> ModelMigration Evergreen.V18.Types.BackendModel Evergreen.V18.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V17.Types.FrontendMsg -> MsgMigration Evergreen.V18.Types.FrontendMsg Evergreen.V18.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V17.Types.ToBackend -> MsgMigration Evergreen.V18.Types.ToBackend Evergreen.V18.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V17.Types.BackendMsg -> MsgMigration Evergreen.V18.Types.BackendMsg Evergreen.V18.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V17.Types.ToFrontend -> MsgMigration Evergreen.V18.Types.ToFrontend Evergreen.V18.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V17.Types.BackendModel -> Evergreen.V18.Types.BackendModel
migrate_Types_BackendModel old =
    { now = old.now
    , users = old.users |> Dict.map (\k -> migrate_Types_User)
    , sessions = old.sessions
    , listings = old.listings |> Dict.map (\k -> migrate_Types_Listing)
    , offers = old.offers |> Dict.map (\k -> migrate_Types_Offer)
    , reports = old.reports
    , adminLog = old.adminLog
    , nextId = old.nextId
    , pendingAuths = old.pendingAuths
    }


migrate_Types_FrontendModel : Evergreen.V17.Types.FrontendModel -> Evergreen.V18.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , now = old.now
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    , me = old.me |> Maybe.map migrate_Types_Me
    , loaded = old.loaded
    , listings = old.listings |> Dict.map (\k -> migrate_Types_Listing)
    , offers = old.offers |> Dict.map (\k -> migrate_Types_Offer)
    , traders = old.traders
    , filters = old.filters |> migrate_Types_MarketFilters
    , filtersOpen = old.filtersOpen
    , claimName = old.claimName
    , claimError = old.claimError
    , listingForm = old.listingForm |> migrate_Types_ListingForm
    , offerForm = old.offerForm |> migrate_Types_OfferForm
    , reportForm = old.reportForm |> migrate_Types_ReportForm
    , previewSignInFor = old.previewSignInFor |> Maybe.map migrate_Types_Provider
    , toast = old.toast
    , tradesTab = old.tradesTab |> migrate_Types_TradesTab
    , admin = old.admin |> Maybe.map migrate_Types_AdminData
    , adminPage = old.adminPage |> migrate_Types_AdminPage
    }


migrate_Auth_Common_AuthChallengeReason : Evergreen.V17.Auth.Common.AuthChallengeReason -> Evergreen.V18.Auth.Common.AuthChallengeReason
migrate_Auth_Common_AuthChallengeReason old =
    case old of
        Evergreen.V17.Auth.Common.AuthSessionMissing ->
            Evergreen.V18.Auth.Common.AuthSessionMissing

        Evergreen.V17.Auth.Common.AuthSessionInvalid ->
            Evergreen.V18.Auth.Common.AuthSessionInvalid

        Evergreen.V17.Auth.Common.AuthSessionExpired ->
            Evergreen.V18.Auth.Common.AuthSessionExpired

        Evergreen.V17.Auth.Common.AuthSessionLoggedOut ->
            Evergreen.V18.Auth.Common.AuthSessionLoggedOut


migrate_Auth_Common_BackendMsg : Evergreen.V17.Auth.Common.BackendMsg -> Evergreen.V18.Auth.Common.BackendMsg
migrate_Auth_Common_BackendMsg old =
    case old of
        Evergreen.V17.Auth.Common.AuthSigninInitiated_ p0 ->
            Evergreen.V18.Auth.Common.AuthSigninInitiated_ p0

        Evergreen.V17.Auth.Common.AuthSigninInitiatedDelayed_ p0 p1 ->
            Evergreen.V18.Auth.Common.AuthSigninInitiatedDelayed_ p0 (p1 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V17.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V18.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6

        Evergreen.V17.Auth.Common.AuthSuccess p0 p1 p2 p3 p4 ->
            Evergreen.V18.Auth.Common.AuthSuccess p0
                p1
                p2
                p3
                (p4 |> Result.mapError migrate_Auth_Common_Error >> Result.map (Tuple.mapBoth migrate_Auth_Common_UserInfo (Maybe.map migrate_Auth_Common_Token)))

        Evergreen.V17.Auth.Common.AuthRenewSession p0 p1 ->
            Evergreen.V18.Auth.Common.AuthRenewSession p0 p1

        Evergreen.V17.Auth.Common.AuthLogout p0 p1 ->
            Evergreen.V18.Auth.Common.AuthLogout p0 p1


migrate_Auth_Common_Error : Evergreen.V17.Auth.Common.Error -> Evergreen.V18.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V17.Auth.Common.ErrStateMismatch ->
            Evergreen.V18.Auth.Common.ErrStateMismatch

        Evergreen.V17.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V18.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V17.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V18.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V17.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V18.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V17.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V18.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V17.Auth.Common.ErrAuthString p0 ->
            Evergreen.V18.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V17.Auth.Common.Flow -> Evergreen.V18.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V17.Auth.Common.Idle ->
            Evergreen.V18.Auth.Common.Idle

        Evergreen.V17.Auth.Common.Requested p0 ->
            Evergreen.V18.Auth.Common.Requested p0

        Evergreen.V17.Auth.Common.Pending ->
            Evergreen.V18.Auth.Common.Pending

        Evergreen.V17.Auth.Common.Authorized p0 p1 ->
            Evergreen.V18.Auth.Common.Authorized p0 p1

        Evergreen.V17.Auth.Common.Authenticated p0 ->
            Evergreen.V18.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V17.Auth.Common.Done p0 ->
            Evergreen.V18.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V17.Auth.Common.Errored p0 ->
            Evergreen.V18.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_ToBackend : Evergreen.V17.Auth.Common.ToBackend -> Evergreen.V18.Auth.Common.ToBackend
migrate_Auth_Common_ToBackend old =
    case old of
        Evergreen.V17.Auth.Common.AuthSigninInitiated p0 ->
            Evergreen.V18.Auth.Common.AuthSigninInitiated p0

        Evergreen.V17.Auth.Common.AuthCallbackReceived p0 p1 p2 p3 ->
            Evergreen.V18.Auth.Common.AuthCallbackReceived p0 p1 p2 p3

        Evergreen.V17.Auth.Common.AuthRenewSessionRequested ->
            Evergreen.V18.Auth.Common.AuthRenewSessionRequested

        Evergreen.V17.Auth.Common.AuthLogoutRequested ->
            Evergreen.V18.Auth.Common.AuthLogoutRequested


migrate_Auth_Common_ToFrontend : Evergreen.V17.Auth.Common.ToFrontend -> Evergreen.V18.Auth.Common.ToFrontend
migrate_Auth_Common_ToFrontend old =
    case old of
        Evergreen.V17.Auth.Common.AuthInitiateSignin p0 ->
            Evergreen.V18.Auth.Common.AuthInitiateSignin p0

        Evergreen.V17.Auth.Common.AuthError p0 ->
            Evergreen.V18.Auth.Common.AuthError (p0 |> migrate_Auth_Common_Error)

        Evergreen.V17.Auth.Common.AuthSessionChallenge p0 ->
            Evergreen.V18.Auth.Common.AuthSessionChallenge (p0 |> migrate_Auth_Common_AuthChallengeReason)


migrate_Auth_Common_Token : Evergreen.V17.Auth.Common.Token -> Evergreen.V18.Auth.Common.Token
migrate_Auth_Common_Token old =
    { methodId = old.methodId
    , token = old.token |> migrate_OAuth_Token
    , created = old.created
    , expires = old.expires
    }


migrate_Auth_Common_UserInfo : Evergreen.V17.Auth.Common.UserInfo -> Evergreen.V18.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Item_Quality : Evergreen.V17.Item.Quality -> Evergreen.V18.Item.Quality
migrate_Item_Quality old =
    case old of
        Evergreen.V17.Item.Normal ->
            Evergreen.V18.Item.Normal

        Evergreen.V17.Item.Good ->
            Evergreen.V18.Item.Good

        Evergreen.V17.Item.Great ->
            Evergreen.V18.Item.Great

        Evergreen.V17.Item.Excellent ->
            Evergreen.V18.Item.Excellent

        Evergreen.V17.Item.Perfect ->
            Evergreen.V18.Item.Perfect

        Evergreen.V17.Item.Eternal ->
            Evergreen.V18.Item.Eternal


migrate_Item_Rarity : Evergreen.V17.Item.Rarity -> Evergreen.V18.Item.Rarity
migrate_Item_Rarity old =
    case old of
        Evergreen.V17.Item.Common ->
            Evergreen.V18.Item.Common

        Evergreen.V17.Item.Uncommon ->
            Evergreen.V18.Item.Uncommon

        Evergreen.V17.Item.Rare ->
            Evergreen.V18.Item.Rare

        Evergreen.V17.Item.Epic ->
            Evergreen.V18.Item.Epic

        Evergreen.V17.Item.Legendary ->
            Evergreen.V18.Item.Legendary

        Evergreen.V17.Item.Ethereal ->
            Evergreen.V18.Item.Ethereal


migrate_Item_Variant : Evergreen.V17.Item.Variant -> Evergreen.V18.Item.Variant
migrate_Item_Variant old =
    { fine = old.fine
    , rare = old.rare
    , quality = old.quality |> Maybe.map migrate_Item_Quality
    }


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V17.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V18.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V17.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V18.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V17.OAuth.ErrorCode -> Evergreen.V18.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V17.OAuth.InvalidRequest ->
            Evergreen.V18.OAuth.InvalidRequest

        Evergreen.V17.OAuth.UnauthorizedClient ->
            Evergreen.V18.OAuth.UnauthorizedClient

        Evergreen.V17.OAuth.AccessDenied ->
            Evergreen.V18.OAuth.AccessDenied

        Evergreen.V17.OAuth.UnsupportedResponseType ->
            Evergreen.V18.OAuth.UnsupportedResponseType

        Evergreen.V17.OAuth.InvalidScope ->
            Evergreen.V18.OAuth.InvalidScope

        Evergreen.V17.OAuth.ServerError ->
            Evergreen.V18.OAuth.ServerError

        Evergreen.V17.OAuth.TemporarilyUnavailable ->
            Evergreen.V18.OAuth.TemporarilyUnavailable

        Evergreen.V17.OAuth.Custom p0 ->
            Evergreen.V18.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V17.OAuth.Token -> Evergreen.V18.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V17.OAuth.Bearer p0 ->
            Evergreen.V18.OAuth.Bearer p0


migrate_Route_Route : Evergreen.V17.Route.Route -> Evergreen.V18.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V17.Route.Home ->
            Evergreen.V18.Route.Home

        Evergreen.V17.Route.Market ->
            Evergreen.V18.Route.Market

        Evergreen.V17.Route.Prices ->
            Evergreen.V18.Route.Prices

        Evergreen.V17.Route.ItemPrice p0 p1 ->
            Evergreen.V18.Route.ItemPrice p0 (p1 |> migrate_Item_Variant)

        Evergreen.V17.Route.ListingPage p0 ->
            Evergreen.V18.Route.ListingPage p0

        Evergreen.V17.Route.NewListing p0 ->
            Evergreen.V18.Route.NewListing (p0 |> Maybe.map (Tuple.mapSecond migrate_Item_Variant))

        Evergreen.V17.Route.MyTrades ->
            Evergreen.V18.Route.MyTrades

        Evergreen.V17.Route.Profile p0 ->
            Evergreen.V18.Route.Profile p0

        Evergreen.V17.Route.Report p0 ->
            Evergreen.V18.Route.Report p0

        Evergreen.V17.Route.SignIn ->
            Evergreen.V18.Route.SignIn

        Evergreen.V17.Route.Onboarding ->
            Evergreen.V18.Route.Onboarding

        Evergreen.V17.Route.Admin ->
            Evergreen.V18.Route.Admin

        Evergreen.V17.Route.NotFound ->
            Evergreen.V18.Route.NotFound


migrate_Types_AdminAction : Evergreen.V17.Types.AdminAction -> Evergreen.V18.Types.AdminAction
migrate_Types_AdminAction old =
    case old of
        Evergreen.V17.Types.DeleteListing p0 ->
            Evergreen.V18.Types.DeleteListing p0

        Evergreen.V17.Types.DeleteOffer p0 ->
            Evergreen.V18.Types.DeleteOffer p0

        Evergreen.V17.Types.BanPlayer p0 p1 ->
            Evergreen.V18.Types.BanPlayer p0 p1

        Evergreen.V17.Types.UnbanPlayer p0 ->
            Evergreen.V18.Types.UnbanPlayer p0

        Evergreen.V17.Types.ReleaseName p0 ->
            Evergreen.V18.Types.ReleaseName p0

        Evergreen.V17.Types.SetReportResolved p0 p1 ->
            Evergreen.V18.Types.SetReportResolved p0 p1


migrate_Types_AdminData : Evergreen.V17.Types.AdminData -> Evergreen.V18.Types.AdminData
migrate_Types_AdminData old =
    { accounts = old.accounts
    , users = old.users
    , listings = old.listings |> List.map migrate_Types_Listing
    , offers = old.offers |> List.map migrate_Types_Offer
    , reports = old.reports
    , log = old.log
    }


migrate_Types_AdminPage : Evergreen.V17.Types.AdminPage -> Evergreen.V18.Types.AdminPage
migrate_Types_AdminPage old =
    { tab = old.tab |> migrate_Types_AdminTab
    , search = old.search
    , confirming = old.confirming |> Maybe.map migrate_Types_AdminAction
    , banReason = old.banReason
    }


migrate_Types_AdminTab : Evergreen.V17.Types.AdminTab -> Evergreen.V18.Types.AdminTab
migrate_Types_AdminTab old =
    case old of
        Evergreen.V17.Types.AdminReports ->
            Evergreen.V18.Types.AdminReports

        Evergreen.V17.Types.AdminListings ->
            Evergreen.V18.Types.AdminListings

        Evergreen.V17.Types.AdminPlayers ->
            Evergreen.V18.Types.AdminPlayers

        Evergreen.V17.Types.AdminLog ->
            Evergreen.V18.Types.AdminLog


migrate_Types_BackendMsg : Evergreen.V17.Types.BackendMsg -> Evergreen.V18.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V17.Types.ClientConnected p0 p1 ->
            Evergreen.V18.Types.ClientConnected p0 p1

        Evergreen.V17.Types.ClientDisconnected p0 p1 ->
            Evergreen.V18.Types.ClientDisconnected p0 p1

        Evergreen.V17.Types.AuthBackendMsg p0 ->
            Evergreen.V18.Types.AuthBackendMsg (p0 |> migrate_Auth_Common_BackendMsg)

        Evergreen.V17.Types.GotTime p0 ->
            Evergreen.V18.Types.GotTime p0

        Evergreen.V17.Types.BackendTick p0 ->
            Evergreen.V18.Types.BackendTick p0

        Evergreen.V17.Types.FromFrontendAt p0 p1 p2 p3 ->
            Evergreen.V18.Types.FromFrontendAt p0 p1 (p2 |> migrate_Types_ToBackend) p3


migrate_Types_Claim : Evergreen.V17.Types.Claim -> Evergreen.V18.Types.Claim
migrate_Types_Claim old =
    { name = old.name
    , status = old.status |> migrate_Types_ClaimStatus
    }


migrate_Types_ClaimStatus : Evergreen.V17.Types.ClaimStatus -> Evergreen.V18.Types.ClaimStatus
migrate_Types_ClaimStatus old =
    case old of
        Evergreen.V17.Types.PreviewUnverified ->
            Evergreen.V18.Types.PreviewUnverified


migrate_Types_InitialData : Evergreen.V17.Types.InitialData -> Evergreen.V18.Types.InitialData
migrate_Types_InitialData old =
    { listings = old.listings |> List.map migrate_Types_Listing
    , offers = old.offers |> List.map migrate_Types_Offer
    , traders = old.traders
    }


migrate_Types_Listing : Evergreen.V17.Types.Listing -> Evergreen.V18.Types.Listing
migrate_Types_Listing old =
    { id = old.id
    , trader = old.trader
    , itemId = old.itemId
    , variant = old.variant |> migrate_Item_Variant
    , side = old.side |> migrate_Types_Side
    , payment = old.payment |> migrate_Types_Payment
    , quantity = old.quantity
    , note = old.note
    , createdAt = old.createdAt
    , liveAt = old.liveAt
    , closed = old.closed
    }


migrate_Types_ListingDraft : Evergreen.V17.Types.ListingDraft -> Evergreen.V18.Types.ListingDraft
migrate_Types_ListingDraft old =
    { itemId = old.itemId
    , variant = old.variant |> migrate_Item_Variant
    , side = old.side |> migrate_Types_Side
    , payment = old.payment |> migrate_Types_Payment
    , quantity = old.quantity
    , note = old.note
    }


migrate_Types_ListingForm : Evergreen.V17.Types.ListingForm -> Evergreen.V18.Types.ListingForm
migrate_Types_ListingForm old =
    { itemQuery = old.itemQuery
    , itemId = old.itemId
    , quality = old.quality |> migrate_Item_Quality
    , fine = old.fine
    , rare = old.rare
    , side = old.side |> migrate_Types_Side
    , quantity = old.quantity
    , price = old.price
    , note = old.note
    , error = old.error
    , submitting = old.submitting
    }


migrate_Types_MarketFilters : Evergreen.V17.Types.MarketFilters -> Evergreen.V18.Types.MarketFilters
migrate_Types_MarketFilters old =
    { tab = old.tab |> migrate_Types_MarketTab
    , rarities = old.rarities |> List.map migrate_Item_Rarity
    , qualities = old.qualities |> List.map migrate_Item_Quality
    , fineOnly = old.fineOnly
    , sort = old.sort |> migrate_Types_MarketSort
    , hideOutliers = old.hideOutliers
    , search = old.search
    }


migrate_Types_MarketSort : Evergreen.V17.Types.MarketSort -> Evergreen.V18.Types.MarketSort
migrate_Types_MarketSort old =
    case old of
        Evergreen.V17.Types.Newest ->
            Evergreen.V18.Types.Newest

        Evergreen.V17.Types.PriceLow ->
            Evergreen.V18.Types.PriceLow

        Evergreen.V17.Types.PriceHigh ->
            Evergreen.V18.Types.PriceHigh


migrate_Types_MarketTab : Evergreen.V17.Types.MarketTab -> Evergreen.V18.Types.MarketTab
migrate_Types_MarketTab old =
    case old of
        Evergreen.V17.Types.AllListings ->
            Evergreen.V18.Types.AllListings

        Evergreen.V17.Types.SellingTab ->
            Evergreen.V18.Types.SellingTab

        Evergreen.V17.Types.BuyingTab ->
            Evergreen.V18.Types.BuyingTab


migrate_Types_Me : Evergreen.V17.Types.Me -> Evergreen.V18.Types.Me
migrate_Types_Me old =
    { provider = old.provider |> migrate_Types_Provider
    , isPreviewLogin = old.isPreviewLogin
    , claim = old.claim |> Maybe.map migrate_Types_Claim
    , isAdmin = old.isAdmin
    , ban = old.ban
    , timersNoticeDismissed = False
    }


migrate_Types_Offer : Evergreen.V17.Types.Offer -> Evergreen.V18.Types.Offer
migrate_Types_Offer old =
    { id = old.id
    , listingId = old.listingId
    , from = old.from
    , price = old.price
    , message = old.message
    , at = old.at
    , status = old.status |> migrate_Types_OfferStatus
    }


migrate_Types_OfferForm : Evergreen.V17.Types.OfferForm -> Evergreen.V18.Types.OfferForm
migrate_Types_OfferForm old =
    old


migrate_Types_OfferStatus : Evergreen.V17.Types.OfferStatus -> Evergreen.V18.Types.OfferStatus
migrate_Types_OfferStatus old =
    case old of
        Evergreen.V17.Types.OfferOpen ->
            Evergreen.V18.Types.OfferOpen

        Evergreen.V17.Types.OfferAccepted ->
            Evergreen.V18.Types.OfferAccepted

        Evergreen.V17.Types.OfferDeclined ->
            Evergreen.V18.Types.OfferDeclined

        Evergreen.V17.Types.OfferWithdrawn ->
            Evergreen.V18.Types.OfferWithdrawn


migrate_Types_Payment : Evergreen.V17.Types.Payment -> Evergreen.V18.Types.Payment
migrate_Types_Payment old =
    case old of
        Evergreen.V17.Types.Coins p0 ->
            Evergreen.V18.Types.Coins p0


migrate_Types_Provider : Evergreen.V17.Types.Provider -> Evergreen.V18.Types.Provider
migrate_Types_Provider old =
    case old of
        Evergreen.V17.Types.Discord ->
            Evergreen.V18.Types.Discord


migrate_Types_ReportForm : Evergreen.V17.Types.ReportForm -> Evergreen.V18.Types.ReportForm
migrate_Types_ReportForm old =
    old


migrate_Types_Side : Evergreen.V17.Types.Side -> Evergreen.V18.Types.Side
migrate_Types_Side old =
    case old of
        Evergreen.V17.Types.Selling ->
            Evergreen.V18.Types.Selling

        Evergreen.V17.Types.Buying ->
            Evergreen.V18.Types.Buying


migrate_Types_ToBackend : Evergreen.V17.Types.ToBackend -> Evergreen.V18.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V17.Types.AuthToBackend p0 ->
            Evergreen.V18.Types.AuthToBackend (p0 |> migrate_Auth_Common_ToBackend)

        Evergreen.V17.Types.PreviewSignIn p0 ->
            Evergreen.V18.Types.PreviewSignIn (p0 |> migrate_Types_Provider)

        Evergreen.V17.Types.PreviewAdminSignIn ->
            Evergreen.V18.Types.PreviewAdminSignIn

        Evergreen.V17.Types.SignOut ->
            Evergreen.V18.Types.SignOut

        Evergreen.V17.Types.ClaimName p0 ->
            Evergreen.V18.Types.ClaimName p0

        Evergreen.V17.Types.CreateListing p0 ->
            Evergreen.V18.Types.CreateListing (p0 |> migrate_Types_ListingDraft)

        Evergreen.V17.Types.CloseListing p0 ->
            Evergreen.V18.Types.CloseListing p0

        Evergreen.V17.Types.MakeOffer p0 p1 p2 ->
            Evergreen.V18.Types.MakeOffer p0 p1 p2

        Evergreen.V17.Types.WithdrawOffer p0 ->
            Evergreen.V18.Types.WithdrawOffer p0

        Evergreen.V17.Types.RespondToOffer p0 p1 ->
            Evergreen.V18.Types.RespondToOffer p0 p1

        Evergreen.V17.Types.SubmitReport p0 p1 p2 ->
            Evergreen.V18.Types.SubmitReport p0 p1 p2

        Evergreen.V17.Types.AdminLoad ->
            Evergreen.V18.Types.AdminLoad

        Evergreen.V17.Types.AdminRequest p0 ->
            Evergreen.V18.Types.AdminRequest (p0 |> migrate_Types_AdminAction)



migrate_Types_ToFrontend : Evergreen.V17.Types.ToFrontend -> Evergreen.V18.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V17.Types.AuthToFrontend p0 ->
            Evergreen.V18.Types.AuthToFrontend (p0 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V17.Types.InitialDataSent p0 ->
            Evergreen.V18.Types.InitialDataSent (p0 |> migrate_Types_InitialData)

        Evergreen.V17.Types.YouAre p0 ->
            Evergreen.V18.Types.YouAre (p0 |> Maybe.map migrate_Types_Me)

        Evergreen.V17.Types.ListingUpserted p0 ->
            Evergreen.V18.Types.ListingUpserted (p0 |> migrate_Types_Listing)

        Evergreen.V17.Types.ListingRemoved p0 ->
            Evergreen.V18.Types.ListingRemoved p0

        Evergreen.V17.Types.OfferUpserted p0 ->
            Evergreen.V18.Types.OfferUpserted (p0 |> migrate_Types_Offer)

        Evergreen.V17.Types.OfferRemoved p0 ->
            Evergreen.V18.Types.OfferRemoved p0

        Evergreen.V17.Types.TraderUpserted p0 ->
            Evergreen.V18.Types.TraderUpserted (p0 |> migrate_Types_Trader)

        Evergreen.V17.Types.TraderRemoved p0 ->
            Evergreen.V18.Types.TraderRemoved p0

        Evergreen.V17.Types.ClaimRejected p0 ->
            Evergreen.V18.Types.ClaimRejected p0

        Evergreen.V17.Types.ListingCreated p0 ->
            Evergreen.V18.Types.ListingCreated p0

        Evergreen.V17.Types.ReportReceived ->
            Evergreen.V18.Types.ReportReceived

        Evergreen.V17.Types.ActionFailed p0 ->
            Evergreen.V18.Types.ActionFailed p0

        Evergreen.V17.Types.AdminDataSent p0 ->
            Evergreen.V18.Types.AdminDataSent (p0 |> migrate_Types_AdminData)


migrate_Types_Trader : Evergreen.V17.Types.Trader -> Evergreen.V18.Types.Trader
migrate_Types_Trader old =
    old


migrate_Types_TradesTab : Evergreen.V17.Types.TradesTab -> Evergreen.V18.Types.TradesTab
migrate_Types_TradesTab old =
    case old of
        Evergreen.V17.Types.ReceivedTab ->
            Evergreen.V18.Types.ReceivedTab

        Evergreen.V17.Types.SentTab ->
            Evergreen.V18.Types.SentTab

        Evergreen.V17.Types.MyListingsTab ->
            Evergreen.V18.Types.MyListingsTab


migrate_Types_User : Evergreen.V17.Types.User -> Evergreen.V18.Types.User
migrate_Types_User old =
    { id = old.id
    , provider = old.provider |> migrate_Types_Provider
    , isPreviewLogin = old.isPreviewLogin
    , oauthUsername = old.oauthUsername
    , claim = old.claim |> Maybe.map migrate_Types_Claim
    , joinedAt = old.joinedAt
    , ban = old.ban
    , timersNoticeDismissed = False
    }
