module Evergreen.Migrate.V25 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V18.Auth.Common
import Evergreen.V18.Item
import Evergreen.V18.OAuth
import Evergreen.V18.OAuth.AuthorizationCode
import Evergreen.V18.Route
import Evergreen.V18.Types
import Evergreen.V25.Auth.Common
import Evergreen.V25.Item
import Evergreen.V25.OAuth
import Evergreen.V25.OAuth.AuthorizationCode
import Evergreen.V25.Route
import Evergreen.V25.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V18.Types.FrontendModel -> ModelMigration Evergreen.V25.Types.FrontendModel Evergreen.V25.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V18.Types.BackendModel -> ModelMigration Evergreen.V25.Types.BackendModel Evergreen.V25.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V18.Types.FrontendMsg -> MsgMigration Evergreen.V25.Types.FrontendMsg Evergreen.V25.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V18.Types.ToBackend -> MsgMigration Evergreen.V25.Types.ToBackend Evergreen.V25.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V18.Types.BackendMsg -> MsgMigration Evergreen.V25.Types.BackendMsg Evergreen.V25.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V18.Types.ToFrontend -> MsgMigration Evergreen.V25.Types.ToFrontend Evergreen.V25.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V18.Types.BackendModel -> Evergreen.V25.Types.BackendModel
migrate_Types_BackendModel old =
    { now = old.now
    , users = old.users |> Dict.map (\k -> migrate_Types_User)
    , sessions = old.sessions
    , listings = old.listings |> Dict.map (\k -> migrate_Types_Listing)
    , offers = old.offers |> Dict.map (\k -> migrate_Types_Offer)
    , reports = old.reports
    , adminLog = old.adminLog
    , nextId = old.nextId
    , pendingAuths = old.pendingAuths
    }


migrate_Types_FrontendModel : Evergreen.V18.Types.FrontendModel -> Evergreen.V25.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Route_Route
    , now = old.now
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    , me = old.me |> Maybe.map migrate_Types_Me
    , loaded = old.loaded
    , listings = old.listings |> Dict.map (\k -> migrate_Types_Listing)
    , offers = old.offers |> Dict.map (\k -> migrate_Types_Offer)
    , traders = old.traders
    , filters = old.filters |> migrate_Types_MarketFilters
    , filtersOpen = old.filtersOpen
    , claimName = old.claimName
    , claimError = old.claimError
    , listingForm = old.listingForm |> migrate_Types_ListingForm
    , offerForm = old.offerForm |> migrate_Types_OfferForm
    , fellThroughForm = Nothing
    , reportForm = old.reportForm |> migrate_Types_ReportForm
    , previewSignInFor = old.previewSignInFor |> Maybe.map migrate_Types_Provider
    , toast = old.toast
    , tradesTab = old.tradesTab |> migrate_Types_TradesTab
    , admin = old.admin |> Maybe.map migrate_Types_AdminData
    , adminPage = old.adminPage |> migrate_Types_AdminPage
    }


migrate_Auth_Common_AuthChallengeReason : Evergreen.V18.Auth.Common.AuthChallengeReason -> Evergreen.V25.Auth.Common.AuthChallengeReason
migrate_Auth_Common_AuthChallengeReason old =
    case old of
        Evergreen.V18.Auth.Common.AuthSessionMissing ->
            Evergreen.V25.Auth.Common.AuthSessionMissing

        Evergreen.V18.Auth.Common.AuthSessionInvalid ->
            Evergreen.V25.Auth.Common.AuthSessionInvalid

        Evergreen.V18.Auth.Common.AuthSessionExpired ->
            Evergreen.V25.Auth.Common.AuthSessionExpired

        Evergreen.V18.Auth.Common.AuthSessionLoggedOut ->
            Evergreen.V25.Auth.Common.AuthSessionLoggedOut


migrate_Auth_Common_BackendMsg : Evergreen.V18.Auth.Common.BackendMsg -> Evergreen.V25.Auth.Common.BackendMsg
migrate_Auth_Common_BackendMsg old =
    case old of
        Evergreen.V18.Auth.Common.AuthSigninInitiated_ p0 ->
            Evergreen.V25.Auth.Common.AuthSigninInitiated_ p0

        Evergreen.V18.Auth.Common.AuthSigninInitiatedDelayed_ p0 p1 ->
            Evergreen.V25.Auth.Common.AuthSigninInitiatedDelayed_ p0 (p1 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V18.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V25.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6

        Evergreen.V18.Auth.Common.AuthSuccess p0 p1 p2 p3 p4 ->
            Evergreen.V25.Auth.Common.AuthSuccess p0
                p1
                p2
                p3
                (p4 |> Result.mapError migrate_Auth_Common_Error >> Result.map (Tuple.mapBoth migrate_Auth_Common_UserInfo (Maybe.map migrate_Auth_Common_Token)))

        Evergreen.V18.Auth.Common.AuthRenewSession p0 p1 ->
            Evergreen.V25.Auth.Common.AuthRenewSession p0 p1

        Evergreen.V18.Auth.Common.AuthLogout p0 p1 ->
            Evergreen.V25.Auth.Common.AuthLogout p0 p1


migrate_Auth_Common_Error : Evergreen.V18.Auth.Common.Error -> Evergreen.V25.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V18.Auth.Common.ErrStateMismatch ->
            Evergreen.V25.Auth.Common.ErrStateMismatch

        Evergreen.V18.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V25.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V18.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V25.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V18.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V25.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V18.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V25.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V18.Auth.Common.ErrAuthString p0 ->
            Evergreen.V25.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V18.Auth.Common.Flow -> Evergreen.V25.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V18.Auth.Common.Idle ->
            Evergreen.V25.Auth.Common.Idle

        Evergreen.V18.Auth.Common.Requested p0 ->
            Evergreen.V25.Auth.Common.Requested p0

        Evergreen.V18.Auth.Common.Pending ->
            Evergreen.V25.Auth.Common.Pending

        Evergreen.V18.Auth.Common.Authorized p0 p1 ->
            Evergreen.V25.Auth.Common.Authorized p0 p1

        Evergreen.V18.Auth.Common.Authenticated p0 ->
            Evergreen.V25.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V18.Auth.Common.Done p0 ->
            Evergreen.V25.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V18.Auth.Common.Errored p0 ->
            Evergreen.V25.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_ToBackend : Evergreen.V18.Auth.Common.ToBackend -> Evergreen.V25.Auth.Common.ToBackend
migrate_Auth_Common_ToBackend old =
    case old of
        Evergreen.V18.Auth.Common.AuthSigninInitiated p0 ->
            Evergreen.V25.Auth.Common.AuthSigninInitiated p0

        Evergreen.V18.Auth.Common.AuthCallbackReceived p0 p1 p2 p3 ->
            Evergreen.V25.Auth.Common.AuthCallbackReceived p0 p1 p2 p3

        Evergreen.V18.Auth.Common.AuthRenewSessionRequested ->
            Evergreen.V25.Auth.Common.AuthRenewSessionRequested

        Evergreen.V18.Auth.Common.AuthLogoutRequested ->
            Evergreen.V25.Auth.Common.AuthLogoutRequested


migrate_Auth_Common_ToFrontend : Evergreen.V18.Auth.Common.ToFrontend -> Evergreen.V25.Auth.Common.ToFrontend
migrate_Auth_Common_ToFrontend old =
    case old of
        Evergreen.V18.Auth.Common.AuthInitiateSignin p0 ->
            Evergreen.V25.Auth.Common.AuthInitiateSignin p0

        Evergreen.V18.Auth.Common.AuthError p0 ->
            Evergreen.V25.Auth.Common.AuthError (p0 |> migrate_Auth_Common_Error)

        Evergreen.V18.Auth.Common.AuthSessionChallenge p0 ->
            Evergreen.V25.Auth.Common.AuthSessionChallenge (p0 |> migrate_Auth_Common_AuthChallengeReason)


migrate_Auth_Common_Token : Evergreen.V18.Auth.Common.Token -> Evergreen.V25.Auth.Common.Token
migrate_Auth_Common_Token old =
    { methodId = old.methodId
    , token = old.token |> migrate_OAuth_Token
    , created = old.created
    , expires = old.expires
    }


migrate_Auth_Common_UserInfo : Evergreen.V18.Auth.Common.UserInfo -> Evergreen.V25.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Item_Quality : Evergreen.V18.Item.Quality -> Evergreen.V25.Item.Quality
migrate_Item_Quality old =
    case old of
        Evergreen.V18.Item.Normal ->
            Evergreen.V25.Item.Normal

        Evergreen.V18.Item.Good ->
            Evergreen.V25.Item.Good

        Evergreen.V18.Item.Great ->
            Evergreen.V25.Item.Great

        Evergreen.V18.Item.Excellent ->
            Evergreen.V25.Item.Excellent

        Evergreen.V18.Item.Perfect ->
            Evergreen.V25.Item.Perfect

        Evergreen.V18.Item.Eternal ->
            Evergreen.V25.Item.Eternal


migrate_Item_Rarity : Evergreen.V18.Item.Rarity -> Evergreen.V25.Item.Rarity
migrate_Item_Rarity old =
    case old of
        Evergreen.V18.Item.Common ->
            Evergreen.V25.Item.Common

        Evergreen.V18.Item.Uncommon ->
            Evergreen.V25.Item.Uncommon

        Evergreen.V18.Item.Rare ->
            Evergreen.V25.Item.Rare

        Evergreen.V18.Item.Epic ->
            Evergreen.V25.Item.Epic

        Evergreen.V18.Item.Legendary ->
            Evergreen.V25.Item.Legendary

        Evergreen.V18.Item.Ethereal ->
            Evergreen.V25.Item.Ethereal


migrate_Item_Variant : Evergreen.V18.Item.Variant -> Evergreen.V25.Item.Variant
migrate_Item_Variant old =
    { fine = old.fine
    , rare = old.rare
    , quality = old.quality |> Maybe.map migrate_Item_Quality
    }


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V18.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V25.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V18.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V25.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V18.OAuth.ErrorCode -> Evergreen.V25.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V18.OAuth.InvalidRequest ->
            Evergreen.V25.OAuth.InvalidRequest

        Evergreen.V18.OAuth.UnauthorizedClient ->
            Evergreen.V25.OAuth.UnauthorizedClient

        Evergreen.V18.OAuth.AccessDenied ->
            Evergreen.V25.OAuth.AccessDenied

        Evergreen.V18.OAuth.UnsupportedResponseType ->
            Evergreen.V25.OAuth.UnsupportedResponseType

        Evergreen.V18.OAuth.InvalidScope ->
            Evergreen.V25.OAuth.InvalidScope

        Evergreen.V18.OAuth.ServerError ->
            Evergreen.V25.OAuth.ServerError

        Evergreen.V18.OAuth.TemporarilyUnavailable ->
            Evergreen.V25.OAuth.TemporarilyUnavailable

        Evergreen.V18.OAuth.Custom p0 ->
            Evergreen.V25.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V18.OAuth.Token -> Evergreen.V25.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V18.OAuth.Bearer p0 ->
            Evergreen.V25.OAuth.Bearer p0


migrate_Route_Route : Evergreen.V18.Route.Route -> Evergreen.V25.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V18.Route.Home ->
            Evergreen.V25.Route.Home

        Evergreen.V18.Route.Market ->
            Evergreen.V25.Route.Market

        Evergreen.V18.Route.Prices ->
            Evergreen.V25.Route.Prices

        Evergreen.V18.Route.ItemPrice p0 p1 ->
            Evergreen.V25.Route.ItemPrice p0 (p1 |> migrate_Item_Variant)

        Evergreen.V18.Route.ListingPage p0 ->
            Evergreen.V25.Route.ListingPage p0

        Evergreen.V18.Route.NewListing p0 ->
            Evergreen.V25.Route.NewListing (p0 |> Maybe.map (Tuple.mapSecond migrate_Item_Variant))

        Evergreen.V18.Route.MyTrades ->
            Evergreen.V25.Route.MyTrades

        Evergreen.V18.Route.Profile p0 ->
            Evergreen.V25.Route.Profile p0

        Evergreen.V18.Route.Report p0 ->
            Evergreen.V25.Route.Report p0

        Evergreen.V18.Route.SignIn ->
            Evergreen.V25.Route.SignIn

        Evergreen.V18.Route.Onboarding ->
            Evergreen.V25.Route.Onboarding

        Evergreen.V18.Route.Admin ->
            Evergreen.V25.Route.Admin

        Evergreen.V18.Route.NotFound ->
            Evergreen.V25.Route.NotFound


migrate_Types_AdminAction : Evergreen.V18.Types.AdminAction -> Evergreen.V25.Types.AdminAction
migrate_Types_AdminAction old =
    case old of
        Evergreen.V18.Types.DeleteListing p0 ->
            Evergreen.V25.Types.DeleteListing p0

        Evergreen.V18.Types.DeleteOffer p0 ->
            Evergreen.V25.Types.DeleteOffer p0

        Evergreen.V18.Types.BanPlayer p0 p1 ->
            Evergreen.V25.Types.BanPlayer p0 p1

        Evergreen.V18.Types.UnbanPlayer p0 ->
            Evergreen.V25.Types.UnbanPlayer p0

        Evergreen.V18.Types.ReleaseName p0 ->
            Evergreen.V25.Types.ReleaseName p0

        Evergreen.V18.Types.SetReportResolved p0 p1 ->
            Evergreen.V25.Types.SetReportResolved p0 p1


migrate_Types_AdminData : Evergreen.V18.Types.AdminData -> Evergreen.V25.Types.AdminData
migrate_Types_AdminData old =
    { accounts = old.accounts
    , users = old.users
    , listings = old.listings |> List.map migrate_Types_Listing
    , offers = old.offers |> List.map migrate_Types_Offer
    , reports = old.reports
    , log = old.log
    }


migrate_Types_AdminPage : Evergreen.V18.Types.AdminPage -> Evergreen.V25.Types.AdminPage
migrate_Types_AdminPage old =
    { tab = old.tab |> migrate_Types_AdminTab
    , search = old.search
    , confirming = old.confirming |> Maybe.map migrate_Types_AdminAction
    , banReason = old.banReason
    }


migrate_Types_AdminTab : Evergreen.V18.Types.AdminTab -> Evergreen.V25.Types.AdminTab
migrate_Types_AdminTab old =
    case old of
        Evergreen.V18.Types.AdminReports ->
            Evergreen.V25.Types.AdminReports

        Evergreen.V18.Types.AdminListings ->
            Evergreen.V25.Types.AdminListings

        Evergreen.V18.Types.AdminPlayers ->
            Evergreen.V25.Types.AdminPlayers

        Evergreen.V18.Types.AdminLog ->
            Evergreen.V25.Types.AdminLog


migrate_Types_BackendMsg : Evergreen.V18.Types.BackendMsg -> Evergreen.V25.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V18.Types.ClientConnected p0 p1 ->
            Evergreen.V25.Types.ClientConnected p0 p1

        Evergreen.V18.Types.ClientDisconnected p0 p1 ->
            Evergreen.V25.Types.ClientDisconnected p0 p1

        Evergreen.V18.Types.AuthBackendMsg p0 ->
            Evergreen.V25.Types.AuthBackendMsg (p0 |> migrate_Auth_Common_BackendMsg)

        Evergreen.V18.Types.GotTime p0 ->
            Evergreen.V25.Types.GotTime p0

        Evergreen.V18.Types.BackendTick p0 ->
            Evergreen.V25.Types.BackendTick p0

        Evergreen.V18.Types.FromFrontendAt p0 p1 p2 p3 ->
            Evergreen.V25.Types.FromFrontendAt p0 p1 (p2 |> migrate_Types_ToBackend) p3


migrate_Types_Claim : Evergreen.V18.Types.Claim -> Evergreen.V25.Types.Claim
migrate_Types_Claim old =
    { name = old.name
    , status = old.status |> migrate_Types_ClaimStatus
    }


migrate_Types_ClaimStatus : Evergreen.V18.Types.ClaimStatus -> Evergreen.V25.Types.ClaimStatus
migrate_Types_ClaimStatus old =
    case old of
        Evergreen.V18.Types.PreviewUnverified ->
            Evergreen.V25.Types.PreviewUnverified


migrate_Types_FrontendMsg : Evergreen.V18.Types.FrontendMsg -> Evergreen.V25.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V18.Types.UrlClicked p0 ->
            Evergreen.V25.Types.UrlClicked p0

        Evergreen.V18.Types.UrlChanged p0 ->
            Evergreen.V25.Types.UrlChanged p0

        Evergreen.V18.Types.Tick p0 ->
            Evergreen.V25.Types.Tick p0

        Evergreen.V18.Types.ProviderClicked p0 ->
            Evergreen.V25.Types.ProviderClicked (p0 |> migrate_Types_Provider)

        Evergreen.V18.Types.PreviewSignInConfirmed p0 ->
            Evergreen.V25.Types.PreviewSignInConfirmed (p0 |> migrate_Types_Provider)

        Evergreen.V18.Types.PreviewAdminSignInClicked ->
            Evergreen.V25.Types.PreviewAdminSignInClicked

        Evergreen.V18.Types.PreviewSignInCancelled ->
            Evergreen.V25.Types.PreviewSignInCancelled

        Evergreen.V18.Types.SignOutClicked ->
            Evergreen.V25.Types.SignOutClicked

        Evergreen.V18.Types.ClaimNameChanged p0 ->
            Evergreen.V25.Types.ClaimNameChanged p0

        Evergreen.V18.Types.ClaimNameSubmitted ->
            Evergreen.V25.Types.ClaimNameSubmitted

        Evergreen.V18.Types.SearchChanged p0 ->
            Evergreen.V25.Types.SearchChanged p0

        Evergreen.V18.Types.TabSelected p0 ->
            Evergreen.V25.Types.TabSelected (p0 |> migrate_Types_MarketTab)

        Evergreen.V18.Types.SortSelected p0 ->
            Evergreen.V25.Types.SortSelected (p0 |> migrate_Types_MarketSort)

        Evergreen.V18.Types.RarityToggled p0 ->
            Evergreen.V25.Types.RarityToggled (p0 |> migrate_Item_Rarity)

        Evergreen.V18.Types.QualityToggled p0 ->
            Evergreen.V25.Types.QualityToggled (p0 |> migrate_Item_Quality)

        Evergreen.V18.Types.FineOnlyToggled ->
            Evergreen.V25.Types.FineOnlyToggled

        Evergreen.V18.Types.HideOutliersToggled ->
            Evergreen.V25.Types.HideOutliersToggled

        Evergreen.V18.Types.FiltersToggled ->
            Evergreen.V25.Types.FiltersToggled

        Evergreen.V18.Types.NoticeDismissed ->
            Evergreen.V25.Types.NoticeDismissed

        Evergreen.V18.Types.ListingItemQueryChanged p0 ->
            Evergreen.V25.Types.ListingItemQueryChanged p0

        Evergreen.V18.Types.ListingItemPicked p0 ->
            Evergreen.V25.Types.ListingItemPicked p0

        Evergreen.V18.Types.ListingItemCleared ->
            Evergreen.V25.Types.ListingItemCleared

        Evergreen.V18.Types.ListingQualityPicked p0 ->
            Evergreen.V25.Types.ListingQualityPicked (p0 |> migrate_Item_Quality)

        Evergreen.V18.Types.ListingFineToggled p0 ->
            Evergreen.V25.Types.ListingFineToggled p0

        Evergreen.V18.Types.ListingRareToggled p0 ->
            Evergreen.V25.Types.ListingRareToggled p0

        Evergreen.V18.Types.ListingSidePicked p0 ->
            Evergreen.V25.Types.ListingSidePicked (p0 |> migrate_Types_Side)

        Evergreen.V18.Types.ListingQuantityChanged p0 ->
            Evergreen.V25.Types.ListingQuantityChanged p0

        Evergreen.V18.Types.ListingPriceChanged p0 ->
            Evergreen.V25.Types.ListingPriceChanged p0

        Evergreen.V18.Types.ListingNoteChanged p0 ->
            Evergreen.V25.Types.ListingNoteChanged p0

        Evergreen.V18.Types.ListingSubmitted ->
            Evergreen.V25.Types.ListingSubmitted

        Evergreen.V18.Types.CloseListingClicked p0 ->
            Evergreen.V25.Types.CloseListingClicked p0

        Evergreen.V18.Types.OfferCounterToggled p0 ->
            Evergreen.V25.Types.OfferCounterToggled p0

        Evergreen.V18.Types.OfferPriceChanged p0 ->
            Evergreen.V25.Types.OfferPriceChanged p0

        Evergreen.V18.Types.OfferMessageChanged p0 ->
            Evergreen.V25.Types.OfferMessageChanged p0

        Evergreen.V18.Types.OfferSubmitted p0 ->
            Evergreen.V25.Types.OfferSubmitted p0

        Evergreen.V18.Types.WithdrawOfferClicked p0 ->
            Evergreen.V25.Types.WithdrawOfferClicked p0

        Evergreen.V18.Types.RespondToOfferClicked p0 p1 ->
            Evergreen.V25.Types.RespondToOfferClicked p0 p1

        Evergreen.V18.Types.ReportReasonToggled p0 ->
            Evergreen.V25.Types.ReportReasonToggled p0

        Evergreen.V18.Types.ReportDetailsChanged p0 ->
            Evergreen.V25.Types.ReportDetailsChanged p0

        Evergreen.V18.Types.ReportSubmitted ->
            Evergreen.V25.Types.ReportSubmitted

        Evergreen.V18.Types.ToastDismissed ->
            Evergreen.V25.Types.ToastDismissed

        Evergreen.V18.Types.TradesTabSelected p0 ->
            Evergreen.V25.Types.TradesTabSelected (p0 |> migrate_Types_TradesTab)

        Evergreen.V18.Types.AdminTabSelected p0 ->
            Evergreen.V25.Types.AdminTabSelected (p0 |> migrate_Types_AdminTab)

        Evergreen.V18.Types.AdminSearchChanged p0 ->
            Evergreen.V25.Types.AdminSearchChanged p0

        Evergreen.V18.Types.AdminActionClicked p0 ->
            Evergreen.V25.Types.AdminActionClicked (p0 |> migrate_Types_AdminAction)

        Evergreen.V18.Types.AdminBanReasonChanged p0 ->
            Evergreen.V25.Types.AdminBanReasonChanged p0

        Evergreen.V18.Types.AdminConfirmed ->
            Evergreen.V25.Types.AdminConfirmed

        Evergreen.V18.Types.AdminCancelled ->
            Evergreen.V25.Types.AdminCancelled

        Evergreen.V18.Types.AdminRefreshClicked ->
            Evergreen.V25.Types.AdminRefreshClicked

        Evergreen.V18.Types.NoOpFrontendMsg ->
            Evergreen.V25.Types.NoOpFrontendMsg


migrate_Types_InitialData : Evergreen.V18.Types.InitialData -> Evergreen.V25.Types.InitialData
migrate_Types_InitialData old =
    { listings = old.listings |> List.map migrate_Types_Listing
    , offers = old.offers |> List.map migrate_Types_Offer
    , traders = old.traders
    }


migrate_Types_Listing : Evergreen.V18.Types.Listing -> Evergreen.V25.Types.Listing
migrate_Types_Listing old =
    { id = old.id
    , trader = old.trader
    , itemId = old.itemId
    , variant = old.variant |> migrate_Item_Variant
    , side = old.side |> migrate_Types_Side
    , payment = old.payment |> migrate_Types_Payment
    , quantity = old.quantity
    , note = old.note
    , createdAt = old.createdAt
    , liveAt = old.liveAt
    , closed = old.closed
    }


migrate_Types_ListingDraft : Evergreen.V18.Types.ListingDraft -> Evergreen.V25.Types.ListingDraft
migrate_Types_ListingDraft old =
    { itemId = old.itemId
    , variant = old.variant |> migrate_Item_Variant
    , side = old.side |> migrate_Types_Side
    , payment = old.payment |> migrate_Types_Payment
    , quantity = old.quantity
    , note = old.note
    }


migrate_Types_ListingForm : Evergreen.V18.Types.ListingForm -> Evergreen.V25.Types.ListingForm
migrate_Types_ListingForm old =
    { itemQuery = old.itemQuery
    , itemId = old.itemId
    , quality = old.quality |> migrate_Item_Quality
    , fine = old.fine
    , rare = old.rare
    , side = old.side |> migrate_Types_Side
    , quantity = old.quantity
    , price = old.price
    , note = old.note
    , error = old.error
    , submitting = old.submitting
    }


migrate_Types_MarketFilters : Evergreen.V18.Types.MarketFilters -> Evergreen.V25.Types.MarketFilters
migrate_Types_MarketFilters old =
    { tab = old.tab |> migrate_Types_MarketTab
    , rarities = old.rarities |> List.map migrate_Item_Rarity
    , qualities = old.qualities |> List.map migrate_Item_Quality
    , fineOnly = old.fineOnly
    , sort = old.sort |> migrate_Types_MarketSort
    , hideOutliers = old.hideOutliers
    , search = old.search
    }


migrate_Types_MarketSort : Evergreen.V18.Types.MarketSort -> Evergreen.V25.Types.MarketSort
migrate_Types_MarketSort old =
    case old of
        Evergreen.V18.Types.Newest ->
            Evergreen.V25.Types.Newest

        Evergreen.V18.Types.PriceLow ->
            Evergreen.V25.Types.PriceLow

        Evergreen.V18.Types.PriceHigh ->
            Evergreen.V25.Types.PriceHigh


migrate_Types_MarketTab : Evergreen.V18.Types.MarketTab -> Evergreen.V25.Types.MarketTab
migrate_Types_MarketTab old =
    case old of
        Evergreen.V18.Types.AllListings ->
            Evergreen.V25.Types.AllListings

        Evergreen.V18.Types.SellingTab ->
            Evergreen.V25.Types.SellingTab

        Evergreen.V18.Types.BuyingTab ->
            Evergreen.V25.Types.BuyingTab


migrate_Types_Me : Evergreen.V18.Types.Me -> Evergreen.V25.Types.Me
migrate_Types_Me old =
    { provider = old.provider |> migrate_Types_Provider
    , isPreviewLogin = old.isPreviewLogin
    , claim = old.claim |> Maybe.map migrate_Types_Claim
    , isAdmin = old.isAdmin
    , ban = old.ban
    , timersNoticeDismissed = old.timersNoticeDismissed
    }


migrate_Types_Offer : Evergreen.V18.Types.Offer -> Evergreen.V25.Types.Offer
migrate_Types_Offer old =
    { id = old.id
    , listingId = old.listingId
    , from = old.from
    , price = old.price
    , message = old.message
    , at = old.at
    , status = old.status |> migrate_Types_OfferStatus
    , listerConfirmed = False
    , offererConfirmed = False
    }


migrate_Types_OfferForm : Evergreen.V18.Types.OfferForm -> Evergreen.V25.Types.OfferForm
migrate_Types_OfferForm old =
    old


migrate_Types_OfferStatus : Evergreen.V18.Types.OfferStatus -> Evergreen.V25.Types.OfferStatus
migrate_Types_OfferStatus old =
    case old of
        Evergreen.V18.Types.OfferOpen ->
            Evergreen.V25.Types.OfferOpen

        Evergreen.V18.Types.OfferAccepted ->
            Evergreen.V25.Types.OfferAccepted

        Evergreen.V18.Types.OfferDeclined ->
            Evergreen.V25.Types.OfferDeclined

        Evergreen.V18.Types.OfferWithdrawn ->
            Evergreen.V25.Types.OfferWithdrawn


migrate_Types_Payment : Evergreen.V18.Types.Payment -> Evergreen.V25.Types.Payment
migrate_Types_Payment old =
    case old of
        Evergreen.V18.Types.Coins p0 ->
            Evergreen.V25.Types.Coins p0


migrate_Types_Provider : Evergreen.V18.Types.Provider -> Evergreen.V25.Types.Provider
migrate_Types_Provider old =
    case old of
        Evergreen.V18.Types.Discord ->
            Evergreen.V25.Types.Discord


migrate_Types_ReportForm : Evergreen.V18.Types.ReportForm -> Evergreen.V25.Types.ReportForm
migrate_Types_ReportForm old =
    old


migrate_Types_Side : Evergreen.V18.Types.Side -> Evergreen.V25.Types.Side
migrate_Types_Side old =
    case old of
        Evergreen.V18.Types.Selling ->
            Evergreen.V25.Types.Selling

        Evergreen.V18.Types.Buying ->
            Evergreen.V25.Types.Buying


migrate_Types_ToBackend : Evergreen.V18.Types.ToBackend -> Evergreen.V25.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V18.Types.AuthToBackend p0 ->
            Evergreen.V25.Types.AuthToBackend (p0 |> migrate_Auth_Common_ToBackend)

        Evergreen.V18.Types.PreviewSignIn p0 ->
            Evergreen.V25.Types.PreviewSignIn (p0 |> migrate_Types_Provider)

        Evergreen.V18.Types.PreviewAdminSignIn ->
            Evergreen.V25.Types.PreviewAdminSignIn

        Evergreen.V18.Types.SignOut ->
            Evergreen.V25.Types.SignOut

        Evergreen.V18.Types.ClaimName p0 ->
            Evergreen.V25.Types.ClaimName p0

        Evergreen.V18.Types.DismissTimersNotice ->
            Evergreen.V25.Types.DismissTimersNotice

        Evergreen.V18.Types.CreateListing p0 ->
            Evergreen.V25.Types.CreateListing (p0 |> migrate_Types_ListingDraft)

        Evergreen.V18.Types.CloseListing p0 ->
            Evergreen.V25.Types.CloseListing p0

        Evergreen.V18.Types.MakeOffer p0 p1 p2 ->
            Evergreen.V25.Types.MakeOffer p0 p1 p2

        Evergreen.V18.Types.WithdrawOffer p0 ->
            Evergreen.V25.Types.WithdrawOffer p0

        Evergreen.V18.Types.RespondToOffer p0 p1 ->
            Evergreen.V25.Types.RespondToOffer p0 p1

        Evergreen.V18.Types.SubmitReport p0 p1 p2 ->
            Evergreen.V25.Types.SubmitReport p0 p1 p2

        Evergreen.V18.Types.AdminLoad ->
            Evergreen.V25.Types.AdminLoad

        Evergreen.V18.Types.AdminRequest p0 ->
            Evergreen.V25.Types.AdminRequest (p0 |> migrate_Types_AdminAction)


migrate_Types_ToFrontend : Evergreen.V18.Types.ToFrontend -> Evergreen.V25.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V18.Types.AuthToFrontend p0 ->
            Evergreen.V25.Types.AuthToFrontend (p0 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V18.Types.InitialDataSent p0 ->
            Evergreen.V25.Types.InitialDataSent (p0 |> migrate_Types_InitialData)

        Evergreen.V18.Types.YouAre p0 ->
            Evergreen.V25.Types.YouAre (p0 |> Maybe.map migrate_Types_Me)

        Evergreen.V18.Types.ListingUpserted p0 ->
            Evergreen.V25.Types.ListingUpserted (p0 |> migrate_Types_Listing)

        Evergreen.V18.Types.ListingRemoved p0 ->
            Evergreen.V25.Types.ListingRemoved p0

        Evergreen.V18.Types.OfferUpserted p0 ->
            Evergreen.V25.Types.OfferUpserted (p0 |> migrate_Types_Offer)

        Evergreen.V18.Types.OfferRemoved p0 ->
            Evergreen.V25.Types.OfferRemoved p0

        Evergreen.V18.Types.TraderUpserted p0 ->
            Evergreen.V25.Types.TraderUpserted (p0 |> migrate_Types_Trader)

        Evergreen.V18.Types.TraderRemoved p0 ->
            Evergreen.V25.Types.TraderRemoved p0

        Evergreen.V18.Types.ClaimRejected p0 ->
            Evergreen.V25.Types.ClaimRejected p0

        Evergreen.V18.Types.ListingCreated p0 ->
            Evergreen.V25.Types.ListingCreated p0

        Evergreen.V18.Types.ReportReceived ->
            Evergreen.V25.Types.ReportReceived

        Evergreen.V18.Types.ActionFailed p0 ->
            Evergreen.V25.Types.ActionFailed p0

        Evergreen.V18.Types.AdminDataSent p0 ->
            Evergreen.V25.Types.AdminDataSent (p0 |> migrate_Types_AdminData)


migrate_Types_Trader : Evergreen.V18.Types.Trader -> Evergreen.V25.Types.Trader
migrate_Types_Trader old =
    old


migrate_Types_TradesTab : Evergreen.V18.Types.TradesTab -> Evergreen.V25.Types.TradesTab
migrate_Types_TradesTab old =
    case old of
        Evergreen.V18.Types.ReceivedTab ->
            Evergreen.V25.Types.ReceivedTab

        Evergreen.V18.Types.SentTab ->
            Evergreen.V25.Types.SentTab

        Evergreen.V18.Types.MyListingsTab ->
            Evergreen.V25.Types.MyListingsTab


migrate_Types_User : Evergreen.V18.Types.User -> Evergreen.V25.Types.User
migrate_Types_User old =
    { id = old.id
    , provider = old.provider |> migrate_Types_Provider
    , isPreviewLogin = old.isPreviewLogin
    , oauthUsername = old.oauthUsername
    , claim = old.claim |> Maybe.map migrate_Types_Claim
    , joinedAt = old.joinedAt
    , ban = old.ban
    , timersNoticeDismissed = old.timersNoticeDismissed
    }
