module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Auth.Common
import Evergreen.V1.Item
import Evergreen.V1.OAuth
import Evergreen.V1.OAuth.AuthorizationCode
import Evergreen.V1.Types
import Evergreen.V4.Auth.Common
import Evergreen.V4.Item
import Evergreen.V4.OAuth
import Evergreen.V4.OAuth.AuthorizationCode
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    case old of
        Evergreen.V1.Types.NewCoinAmountClicked ->
            MsgOldValueIgnored

        _ ->
            MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    case old of
        Evergreen.V1.Types.NewCoinAmount ->
            MsgOldValueIgnored

        _ ->
            MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    case old of
        Evergreen.V1.Types.FromFrontendAt _ _ Evergreen.V1.Types.NewCoinAmount _ ->
            MsgOldValueIgnored

        _ ->
            MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Auth_Common_AuthChallengeReason : Evergreen.V1.Auth.Common.AuthChallengeReason -> Evergreen.V4.Auth.Common.AuthChallengeReason
migrate_Auth_Common_AuthChallengeReason old =
    case old of
        Evergreen.V1.Auth.Common.AuthSessionMissing ->
            Evergreen.V4.Auth.Common.AuthSessionMissing

        Evergreen.V1.Auth.Common.AuthSessionInvalid ->
            Evergreen.V4.Auth.Common.AuthSessionInvalid

        Evergreen.V1.Auth.Common.AuthSessionExpired ->
            Evergreen.V4.Auth.Common.AuthSessionExpired

        Evergreen.V1.Auth.Common.AuthSessionLoggedOut ->
            Evergreen.V4.Auth.Common.AuthSessionLoggedOut


migrate_Auth_Common_BackendMsg : Evergreen.V1.Auth.Common.BackendMsg -> Evergreen.V4.Auth.Common.BackendMsg
migrate_Auth_Common_BackendMsg old =
    case old of
        Evergreen.V1.Auth.Common.AuthSigninInitiated_ p0 ->
            Evergreen.V4.Auth.Common.AuthSigninInitiated_ p0

        Evergreen.V1.Auth.Common.AuthSigninInitiatedDelayed_ p0 p1 ->
            Evergreen.V4.Auth.Common.AuthSigninInitiatedDelayed_ p0 (p1 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V1.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V4.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6

        Evergreen.V1.Auth.Common.AuthSuccess p0 p1 p2 p3 p4 ->
            Evergreen.V4.Auth.Common.AuthSuccess p0
                p1
                p2
                p3
                (p4 |> Result.mapError migrate_Auth_Common_Error >> Result.map (Tuple.mapBoth migrate_Auth_Common_UserInfo (Maybe.map migrate_Auth_Common_Token)))

        Evergreen.V1.Auth.Common.AuthRenewSession p0 p1 ->
            Evergreen.V4.Auth.Common.AuthRenewSession p0 p1

        Evergreen.V1.Auth.Common.AuthLogout p0 p1 ->
            Evergreen.V4.Auth.Common.AuthLogout p0 p1


migrate_Auth_Common_Error : Evergreen.V1.Auth.Common.Error -> Evergreen.V4.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V1.Auth.Common.ErrStateMismatch ->
            Evergreen.V4.Auth.Common.ErrStateMismatch

        Evergreen.V1.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V4.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V1.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V4.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V1.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V4.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V1.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V4.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V1.Auth.Common.ErrAuthString p0 ->
            Evergreen.V4.Auth.Common.ErrAuthString p0


migrate_Auth_Common_ToBackend : Evergreen.V1.Auth.Common.ToBackend -> Evergreen.V4.Auth.Common.ToBackend
migrate_Auth_Common_ToBackend old =
    case old of
        Evergreen.V1.Auth.Common.AuthSigninInitiated p0 ->
            Evergreen.V4.Auth.Common.AuthSigninInitiated p0

        Evergreen.V1.Auth.Common.AuthCallbackReceived p0 p1 p2 p3 ->
            Evergreen.V4.Auth.Common.AuthCallbackReceived p0 p1 p2 p3

        Evergreen.V1.Auth.Common.AuthRenewSessionRequested ->
            Evergreen.V4.Auth.Common.AuthRenewSessionRequested

        Evergreen.V1.Auth.Common.AuthLogoutRequested ->
            Evergreen.V4.Auth.Common.AuthLogoutRequested


migrate_Auth_Common_ToFrontend : Evergreen.V1.Auth.Common.ToFrontend -> Evergreen.V4.Auth.Common.ToFrontend
migrate_Auth_Common_ToFrontend old =
    case old of
        Evergreen.V1.Auth.Common.AuthInitiateSignin p0 ->
            Evergreen.V4.Auth.Common.AuthInitiateSignin p0

        Evergreen.V1.Auth.Common.AuthError p0 ->
            Evergreen.V4.Auth.Common.AuthError (p0 |> migrate_Auth_Common_Error)

        Evergreen.V1.Auth.Common.AuthSessionChallenge p0 ->
            Evergreen.V4.Auth.Common.AuthSessionChallenge (p0 |> migrate_Auth_Common_AuthChallengeReason)


migrate_Auth_Common_Token : Evergreen.V1.Auth.Common.Token -> Evergreen.V4.Auth.Common.Token
migrate_Auth_Common_Token old =
    { methodId = old.methodId
    , token = old.token |> migrate_OAuth_Token
    , created = old.created
    , expires = old.expires
    }


migrate_Auth_Common_UserInfo : Evergreen.V1.Auth.Common.UserInfo -> Evergreen.V4.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Item_Quality : Evergreen.V1.Item.Quality -> Evergreen.V4.Item.Quality
migrate_Item_Quality old =
    case old of
        Evergreen.V1.Item.Normal ->
            Evergreen.V4.Item.Normal

        Evergreen.V1.Item.Good ->
            Evergreen.V4.Item.Good

        Evergreen.V1.Item.Great ->
            Evergreen.V4.Item.Great

        Evergreen.V1.Item.Excellent ->
            Evergreen.V4.Item.Excellent

        Evergreen.V1.Item.Perfect ->
            Evergreen.V4.Item.Perfect

        Evergreen.V1.Item.Eternal ->
            Evergreen.V4.Item.Eternal


migrate_Item_Rarity : Evergreen.V1.Item.Rarity -> Evergreen.V4.Item.Rarity
migrate_Item_Rarity old =
    case old of
        Evergreen.V1.Item.Common ->
            Evergreen.V4.Item.Common

        Evergreen.V1.Item.Uncommon ->
            Evergreen.V4.Item.Uncommon

        Evergreen.V1.Item.Rare ->
            Evergreen.V4.Item.Rare

        Evergreen.V1.Item.Epic ->
            Evergreen.V4.Item.Epic

        Evergreen.V1.Item.Legendary ->
            Evergreen.V4.Item.Legendary

        Evergreen.V1.Item.Ethereal ->
            Evergreen.V4.Item.Ethereal


migrate_Item_Variant : Evergreen.V1.Item.Variant -> Evergreen.V4.Item.Variant
migrate_Item_Variant old =
    { fine = old.fine
    , quality = old.quality |> Maybe.map migrate_Item_Quality
    }


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V1.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V4.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V1.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V4.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V1.OAuth.ErrorCode -> Evergreen.V4.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V1.OAuth.InvalidRequest ->
            Evergreen.V4.OAuth.InvalidRequest

        Evergreen.V1.OAuth.UnauthorizedClient ->
            Evergreen.V4.OAuth.UnauthorizedClient

        Evergreen.V1.OAuth.AccessDenied ->
            Evergreen.V4.OAuth.AccessDenied

        Evergreen.V1.OAuth.UnsupportedResponseType ->
            Evergreen.V4.OAuth.UnsupportedResponseType

        Evergreen.V1.OAuth.InvalidScope ->
            Evergreen.V4.OAuth.InvalidScope

        Evergreen.V1.OAuth.ServerError ->
            Evergreen.V4.OAuth.ServerError

        Evergreen.V1.OAuth.TemporarilyUnavailable ->
            Evergreen.V4.OAuth.TemporarilyUnavailable

        Evergreen.V1.OAuth.Custom p0 ->
            Evergreen.V4.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V1.OAuth.Token -> Evergreen.V4.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V1.OAuth.Bearer p0 ->
            Evergreen.V4.OAuth.Bearer p0


migrate_Types_BackendMsg : Evergreen.V1.Types.BackendMsg -> Evergreen.V4.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V1.Types.ClientConnected p0 p1 ->
            Evergreen.V4.Types.ClientConnected p0 p1

        Evergreen.V1.Types.ClientDisconnected p0 p1 ->
            Evergreen.V4.Types.ClientDisconnected p0 p1

        Evergreen.V1.Types.AuthBackendMsg p0 ->
            Evergreen.V4.Types.AuthBackendMsg (p0 |> migrate_Auth_Common_BackendMsg)

        Evergreen.V1.Types.GotTime p0 ->
            Evergreen.V4.Types.GotTime p0

        Evergreen.V1.Types.BackendTick p0 ->
            Evergreen.V4.Types.BackendTick p0

        Evergreen.V1.Types.FromFrontendAt p0 p1 p2 p3 ->
            Evergreen.V4.Types.FromFrontendAt p0 p1 (p2 |> migrate_Types_ToBackend) p3


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V4.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V4.Types.UrlChanged p0

        Evergreen.V1.Types.Tick p0 ->
            Evergreen.V4.Types.Tick p0

        Evergreen.V1.Types.ProviderClicked p0 ->
            Evergreen.V4.Types.ProviderClicked (p0 |> migrate_Types_Provider)

        Evergreen.V1.Types.PreviewSignInConfirmed p0 ->
            Evergreen.V4.Types.PreviewSignInConfirmed (p0 |> migrate_Types_Provider)

        Evergreen.V1.Types.PreviewSignInCancelled ->
            Evergreen.V4.Types.PreviewSignInCancelled

        Evergreen.V1.Types.SignOutClicked ->
            Evergreen.V4.Types.SignOutClicked

        Evergreen.V1.Types.ClaimNameChanged p0 ->
            Evergreen.V4.Types.ClaimNameChanged p0

        Evergreen.V1.Types.ClaimNameSubmitted ->
            Evergreen.V4.Types.ClaimNameSubmitted

        Evergreen.V1.Types.NewCoinAmountClicked ->
            -- Dropped by `frontendMsg` before it gets here.
            Evergreen.V4.Types.NoOpFrontendMsg

        Evergreen.V1.Types.ChangeClaimClicked ->
            Evergreen.V4.Types.ChangeClaimClicked

        Evergreen.V1.Types.SkipVerificationClicked ->
            Evergreen.V4.Types.SkipVerificationClicked

        Evergreen.V1.Types.SearchChanged p0 ->
            Evergreen.V4.Types.SearchChanged p0

        Evergreen.V1.Types.TabSelected p0 ->
            Evergreen.V4.Types.TabSelected (p0 |> migrate_Types_MarketTab)

        Evergreen.V1.Types.SortSelected p0 ->
            Evergreen.V4.Types.SortSelected (p0 |> migrate_Types_MarketSort)

        Evergreen.V1.Types.RarityToggled p0 ->
            Evergreen.V4.Types.RarityToggled (p0 |> migrate_Item_Rarity)

        Evergreen.V1.Types.QualityToggled p0 ->
            Evergreen.V4.Types.QualityToggled (p0 |> migrate_Item_Quality)

        Evergreen.V1.Types.FineOnlyToggled ->
            Evergreen.V4.Types.FineOnlyToggled

        Evergreen.V1.Types.HideOutliersToggled ->
            Evergreen.V4.Types.HideOutliersToggled

        Evergreen.V1.Types.FiltersToggled ->
            Evergreen.V4.Types.FiltersToggled

        Evergreen.V1.Types.NoticeDismissed ->
            Evergreen.V4.Types.NoticeDismissed

        Evergreen.V1.Types.ListingItemQueryChanged p0 ->
            Evergreen.V4.Types.ListingItemQueryChanged p0

        Evergreen.V1.Types.ListingItemPicked p0 ->
            Evergreen.V4.Types.ListingItemPicked p0

        Evergreen.V1.Types.ListingItemCleared ->
            Evergreen.V4.Types.ListingItemCleared

        Evergreen.V1.Types.ListingQualityPicked p0 ->
            Evergreen.V4.Types.ListingQualityPicked (p0 |> migrate_Item_Quality)

        Evergreen.V1.Types.ListingFineToggled p0 ->
            Evergreen.V4.Types.ListingFineToggled p0

        Evergreen.V1.Types.ListingSidePicked p0 ->
            Evergreen.V4.Types.ListingSidePicked (p0 |> migrate_Types_Side)

        Evergreen.V1.Types.ListingQuantityChanged p0 ->
            Evergreen.V4.Types.ListingQuantityChanged p0

        Evergreen.V1.Types.ListingPriceChanged p0 ->
            Evergreen.V4.Types.ListingPriceChanged p0

        Evergreen.V1.Types.ListingNoteChanged p0 ->
            Evergreen.V4.Types.ListingNoteChanged p0

        Evergreen.V1.Types.ListingSubmitted ->
            Evergreen.V4.Types.ListingSubmitted

        Evergreen.V1.Types.CloseListingClicked p0 ->
            Evergreen.V4.Types.CloseListingClicked p0

        Evergreen.V1.Types.OfferCounterToggled p0 ->
            Evergreen.V4.Types.OfferCounterToggled p0

        Evergreen.V1.Types.OfferPriceChanged p0 ->
            Evergreen.V4.Types.OfferPriceChanged p0

        Evergreen.V1.Types.OfferMessageChanged p0 ->
            Evergreen.V4.Types.OfferMessageChanged p0

        Evergreen.V1.Types.OfferSubmitted p0 ->
            Evergreen.V4.Types.OfferSubmitted p0

        Evergreen.V1.Types.WithdrawOfferClicked p0 ->
            Evergreen.V4.Types.WithdrawOfferClicked p0

        Evergreen.V1.Types.RespondToOfferClicked p0 p1 ->
            Evergreen.V4.Types.RespondToOfferClicked p0 p1

        Evergreen.V1.Types.ReportReasonToggled p0 ->
            Evergreen.V4.Types.ReportReasonToggled p0

        Evergreen.V1.Types.ReportDetailsChanged p0 ->
            Evergreen.V4.Types.ReportDetailsChanged p0

        Evergreen.V1.Types.ReportSubmitted ->
            Evergreen.V4.Types.ReportSubmitted

        Evergreen.V1.Types.ToastDismissed ->
            Evergreen.V4.Types.ToastDismissed

        Evergreen.V1.Types.TradesTabSelected p0 ->
            Evergreen.V4.Types.TradesTabSelected (p0 |> migrate_Types_TradesTab)

        Evergreen.V1.Types.NoOpFrontendMsg ->
            Evergreen.V4.Types.NoOpFrontendMsg


migrate_Types_ListingDraft : Evergreen.V1.Types.ListingDraft -> Evergreen.V4.Types.ListingDraft
migrate_Types_ListingDraft old =
    { itemId = old.itemId
    , variant = old.variant |> migrate_Item_Variant
    , side = old.side |> migrate_Types_Side
    , payment = old.payment |> migrate_Types_Payment
    , quantity = old.quantity
    , note = old.note
    }


migrate_Types_MarketSort : Evergreen.V1.Types.MarketSort -> Evergreen.V4.Types.MarketSort
migrate_Types_MarketSort old =
    case old of
        Evergreen.V1.Types.Newest ->
            Evergreen.V4.Types.Newest

        Evergreen.V1.Types.PriceLow ->
            Evergreen.V4.Types.PriceLow

        Evergreen.V1.Types.PriceHigh ->
            Evergreen.V4.Types.PriceHigh


migrate_Types_MarketTab : Evergreen.V1.Types.MarketTab -> Evergreen.V4.Types.MarketTab
migrate_Types_MarketTab old =
    case old of
        Evergreen.V1.Types.AllListings ->
            Evergreen.V4.Types.AllListings

        Evergreen.V1.Types.SellingTab ->
            Evergreen.V4.Types.SellingTab

        Evergreen.V1.Types.BuyingTab ->
            Evergreen.V4.Types.BuyingTab


migrate_Types_Payment : Evergreen.V1.Types.Payment -> Evergreen.V4.Types.Payment
migrate_Types_Payment old =
    case old of
        Evergreen.V1.Types.Coins p0 ->
            Evergreen.V4.Types.Coins p0


migrate_Types_Provider : Evergreen.V1.Types.Provider -> Evergreen.V4.Types.Provider
migrate_Types_Provider old =
    case old of
        Evergreen.V1.Types.Discord ->
            Evergreen.V4.Types.Discord


migrate_Types_Side : Evergreen.V1.Types.Side -> Evergreen.V4.Types.Side
migrate_Types_Side old =
    case old of
        Evergreen.V1.Types.Selling ->
            Evergreen.V4.Types.Selling

        Evergreen.V1.Types.Buying ->
            Evergreen.V4.Types.Buying


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V4.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.AuthToBackend p0 ->
            Evergreen.V4.Types.AuthToBackend (p0 |> migrate_Auth_Common_ToBackend)

        Evergreen.V1.Types.PreviewSignIn p0 ->
            Evergreen.V4.Types.PreviewSignIn (p0 |> migrate_Types_Provider)

        Evergreen.V1.Types.SignOut ->
            Evergreen.V4.Types.SignOut

        Evergreen.V1.Types.ClaimName p0 ->
            Evergreen.V4.Types.ClaimName p0

        Evergreen.V1.Types.NewCoinAmount ->
            -- Dropped by `toBackend` / `backendMsg` before it gets here. The
            -- button is gone, so there is no harmless equivalent to map it to.
            Evergreen.V4.Types.SignOut

        Evergreen.V1.Types.SkipVerification ->
            Evergreen.V4.Types.SkipVerification

        Evergreen.V1.Types.CreateListing p0 ->
            Evergreen.V4.Types.CreateListing (p0 |> migrate_Types_ListingDraft)

        Evergreen.V1.Types.CloseListing p0 ->
            Evergreen.V4.Types.CloseListing p0

        Evergreen.V1.Types.MakeOffer p0 p1 p2 ->
            Evergreen.V4.Types.MakeOffer p0 p1 p2

        Evergreen.V1.Types.WithdrawOffer p0 ->
            Evergreen.V4.Types.WithdrawOffer p0

        Evergreen.V1.Types.RespondToOffer p0 p1 ->
            Evergreen.V4.Types.RespondToOffer p0 p1

        Evergreen.V1.Types.SubmitReport p0 p1 p2 ->
            Evergreen.V4.Types.SubmitReport p0 p1 p2


migrate_Types_TradesTab : Evergreen.V1.Types.TradesTab -> Evergreen.V4.Types.TradesTab
migrate_Types_TradesTab old =
    case old of
        Evergreen.V1.Types.ReceivedTab ->
            Evergreen.V4.Types.ReceivedTab

        Evergreen.V1.Types.SentTab ->
            Evergreen.V4.Types.SentTab

        Evergreen.V1.Types.MyListingsTab ->
            Evergreen.V4.Types.MyListingsTab
